import os
import subprocess
from typing import Optional

class GitClient:
    def __init__(self, repo_url: str = None, local_path: str = "../templates-repo"):
        self.repo_url = repo_url or os.getenv('TEMPLATES_REPO', 
            'git@github.com:giovanemere/demo-infra-ai-agent-template-idp.git')
        self.local_path = local_path
        self._setup_repo()
    
    def _setup_repo(self):
        """Clona o actualiza el repositorio local"""
        if not os.path.exists(self.local_path):
            subprocess.run([
                "git", "clone", self.repo_url, self.local_path
            ], check=True)
        else:
            subprocess.run([
                "git", "pull", "origin", "main"
            ], cwd=self.local_path, check=True)
    
    def save_yaml(self, filename: str, content: str, folder: str = "components") -> str:
        """Guarda YAML y hace commit"""
        file_path = os.path.join(self.local_path, folder, filename)
        
        # Crear directorio si no existe
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        # Escribir archivo
        with open(file_path, 'w') as f:
            f.write(content)
        
        # Git add, commit, push
        subprocess.run(["git", "add", "."], cwd=self.local_path, check=True)
        subprocess.run([
            "git", "commit", "-m", f"Add {filename} generated by AI Agent"
        ], cwd=self.local_path, check=True)
        subprocess.run([
            "git", "push", "origin", "main"
        ], cwd=self.local_path, check=True)
        
        return f"https://github.com/giovanemere/demo-infra-ai-agent-template-idp/blob/main/{folder}/{filename}"
